# Generated by Django 2.1.7 on 2019-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Person_step1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=4)),
                ('province', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=8)),
                ('circle', models.CharField(max_length=8)),
                ('username', models.CharField(max_length=8)),
                ('topDegree', models.CharField(max_length=8)),
                ('workyear', models.CharField(max_length=8)),
                ('tel', models.CharField(max_length=8)),
                ('buyer', models.ForeignKey(on_delete=True, to='Buyer.Buyer')),
            ],
        ),
    ]
